project-name: mobilenet_v2
models:
  mobilenet_v2:
    platform: caffe
    prototxt_file_path: ../../../../caffe/mobilenet_v2/mobilenet_v2.prototxt
    caffemodel_file_path: ../../../../caffe/mobilenet_v2/mobilenet_v2.caffemodel
    quantize: true
    source: text
    dataset: ../../../../caffe/mobilenet_v2/dataset.txt
    configs:
      quantized_dtype: asymmetric_quantized-u8
      batch_size: 1
      channel_mean_value: 103.94 116.78 123.68 58.82
      reorder_channel: 2 1 0
